pipeline {
    agent any
    //agent { label 'windows' }
    stages {
        stage('Checkout Code') {
            steps {
                echo 'Fetching code from the repository...'
                git branch: 'test', url: 'https://github.com/gizemcobannnn/psychologists.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                echo 'Installing project dependencies...'
                // If this is an npm project:
                dir('psychologists'){
                bat 'npm install'
                }
            }
        }

        stage('Build Project') {
            steps {
                echo 'Starting build process...'
                // If you have a build command, add it here:
                dir('psychologists') {
                    bat 'npm run build'
                }
            }
        }

        stage('Run Tests') {
            steps {
                echo 'Executing test scripts...'
                // If you have test scripts:
                dir('psychologists'){
                //bat 'npm test'
                //bat 'deploy.bat'
                }
                
            }
        }

        stage('Deploy Application') {
            steps {
                echo 'Starting deployment process...'
                // Add your deployment commands here (e.g., Netlify CLI, FTP upload, Docker deployment, etc.)
                dir('psychologists'){
                //bat 'npm run dev '
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully.'
        }
        failure {
            echo 'Pipeline failed. Check the logs for more details.'
        }
        always {
            echo 'Pipeline execution has finished.'
        }
    }
}
